---

- name: Family RedHat
  when: ansible_os_family == 'RedHat'
  block:

    - name: Install required package (RedHat)
      ansible.builtin.yum:
        name: yum-utils
        state: present

    - name: Execute check for pending restart (RedHat)
      ansible.builtin.command: needs-restarting -r
      check_mode: no
      changed_when: false
      failed_when: restart_required.rc > 1
      register: restart_required

    - name: Flip the boolean if needed (RedHat)
      ansible.builtin.set_fact:
        reboot_needed: true
      when: restart_required.rc == 1

- name: Family Debian
  when: ansible_os_family == 'Debian'
  block:

    - name: Test for Debian reboot file presence (Debian)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: restart_required

    - name: Flip the boolean if needed (Debian)
      ansible.builtin.set_fact:
        reboot_needed: true
      when: restart_required.stat.exists
