---

- block:

    - name: Install required package (RedHat)
      yum:
        name: yum-utils
        state: present

    - name: Execute check for pending restart (RedHat)
      command: needs-restarting -r
      check_mode: no
      changed_when: False
      failed_when: restart_required.rc > 1
      register: restart_required

    - name: Flip the boolean if needed (RedHat)
      set_fact:
        reboot_needed: True
      when: restart_required.rc == 1

  when: ansible_os_family == 'RedHat'

- block:

    - name: Test for Debian reboot file presence (Debian)
      stat:
        path: /var/run/reboot-required
      register: restart_required

    - name: Flip the boolean if needed (Debian)
      set_fact:
        reboot_needed: True
      when: restart_required.stat.exists

  when: ansible_os_family == 'Debian'
