---

- name: Show reboot message  # noqa jinja[spacing]
  ansible.builtin.debug:
    msg: >-
      {%- if reboot_needed | bool -%}
      The server needs to be rebooted.
      {%- else -%}
      No need to reboot the server.
      {%- endif -%}

- name: Execute reboot (async)
  when:
    - ansible_virtualization_type not in [ 'docker', 'container', 'containerd' ]
    - not reboot_postponed | bool
    - reboot_needed | bool or reboot_forced | bool
    - reboot_async | bool
  block:

    - name: Reboot the system
      ansible.builtin.command:
        cmd: reboot
      changed_when: yes
      async: 1
      poll: 0

    - name: Wait remote system to be back
      ansible.builtin.wait_for:
        host: "{{ ansible_host | default(inventory_hostname) }}"
        port: "{{ reboot_port_check | int }}"
        state: started
        delay: 10
        timeout: 300
      delegate_to: localhost

- name: Execute reboot (non-async)
  when:
    - ansible_virtualization_type not in [ 'docker', 'container', 'containerd' ]
    - not reboot_postponed | bool
    - reboot_needed | bool or reboot_forced | bool
    - not reboot_async | bool
  block:

    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout | int }}"
