---

- name: Show reboot message
  ansible.builtin.debug:
    msg: "The server needs to be rebooted"
  when: reboot_needed | bool

- name: Reboot the system
  ansible.builtin.reboot:
    reboot_timeout: >
      {{ reboot_timeout | int }}
  when:
    - ansible_virtualization_type not in [ 'docker', 'container', 'containerd' ]
    - not reboot_postponed | bool
    - reboot_needed | bool or reboot_forced | bool
