---

- name: Show reboot message
  ansible.builtin.debug:
    msg: >-
      {%- if reboot_needed | bool -%}
      The server needs to be rebooted.
      {%- else -%}
      No need to reboot the server.
      {%- endif -%}

- name: Reboot the system
  ansible.builtin.reboot:
    reboot_timeout: >
      {{ reboot_timeout | int }}
  when:
    - ansible_virtualization_type not in [ 'docker', 'container', 'containerd' ]
    - not reboot_postponed | bool
    - reboot_needed | bool or reboot_forced | bool
