---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"
    reboot_forced: True
  tasks:
    - name: Include role 'ansible-role-reboot'
      ansible.builtin.include_role:
        name: ansible-role-reboot
