---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    reboot_forced: True
  tasks:
    - name: Include role 'ansible-role-reboot'
      ansible.builtin.include_role:
        name: ansible-role-reboot
